namespace Vehimap.Desktop.ViewModels;

public enum DesktopFocusTarget
{
    VehicleList,
    VehicleSearch,
    SelectedVehicleTabHeader,
    VehicleDetailPrimaryAction,
    VehicleEditorName,
    VehicleEditorCancel,
    HistoryList,
    HistoryEditorDate,
    FuelList,
    FuelEditorDate,
    ReminderList,
    ReminderEditorTitle,
    MaintenanceList,
    MaintenanceEditorTemplate,
    MaintenanceEditorTitle,
    TimelineSearch,
    TimelineList,
    GlobalSearchBox,
    GlobalSearchList,
    UpcomingOverviewSearch,
    UpcomingOverviewList,
    OverdueOverviewSearch,
    OverdueOverviewList,
    RecordList,
    RecordEditorTitle,
    AuditSearch,
    AuditList,
    CostList,
    CostDetail,
    DashboardAuditList,
    DashboardCostList,
    DashboardTimelineList
}
