; This file is generated by build/release.ps1. Do not edit manually.
;@Ahk2Exe-SetDescription Vehimap
;@Ahk2Exe-SetCompanyName vlcekapps
;@Ahk2Exe-SetFileVersion 1.0.1.0
;@Ahk2Exe-SetProductVersion 1.0.1.0

global AppVersion := "1.0.1"
global AppFileVersion := "1.0.1.0"